Attribute VB_Name = "VisionEnums"
Option Explicit

'VISION_REC_SAMPLE_PERIOD enumeration
Public Const VISION_REC_SAMPLE_PRD_AUTO = 0
Public Const VISION_REC_SAMPLE_PRD_DEFAULT = 1
Public Const VISION_REC_SAMPLE_PRD_1MS = 2
Public Const VISION_REC_SAMPLE_PRD_2MS = 3
Public Const VISION_REC_SAMPLE_PRD_5MS = 4
Public Const VISION_REC_SAMPLE_PRD_10MS = 5
Public Const VISION_REC_SAMPLE_PRD_20MS = 6
Public Const VISION_REC_SAMPLE_PRD_50MS = 7
Public Const VISION_REC_SAMPLE_PRD_100MS = 8
Public Const VISION_REC_SAMPLE_PRD_200MS = 9
Public Const VISION_REC_SAMPLE_PRD_500MS = 10
Public Const VISION_REC_SAMPLE_PRD_1SEC = 11
Public Const VISION_REC_SAMPLE_PRD_2SEC = 12
Public Const VISION_REC_SAMPLE_PRD_5SEC = 13
Public Const VISION_REC_SAMPLE_PRD_10SEC = 14
Public Const VISION_REC_SAMPLE_PRD_EVENT1 = 15
Public Const VISION_REC_SAMPLE_PRD_EVENT2 = 16
Public Const VISION_REC_SAMPLE_PRD_EVENT3 = 17
Public Const VISION_REC_SAMPLE_PRD_EVENT4 = 18
Public Const VISION_REC_SAMPLE_PRD_EVENT5 = 19
Public Const VISION_REC_SAMPLE_PRD_EVENT6 = 20
Public Const VISION_REC_SAMPLE_PRD_EVENT7 = 21
Public Const VISION_REC_SAMPLE_PRD_EVENT8 = 22
Public Const VISION_REC_SAMPLE_PRD_EVENT9 = 23
Public Const VISION_REC_SAMPLE_PRD_100US = 24
Public Const VISION_REC_SAMPLE_PRD_200US = 25
Public Const VISION_REC_SAMPLE_PRD_500US = 26

Public Const VISION_SCREEN_DATALIST = 1
Public Const VISION_SCREEN_RECORDER = 2
Public Const VISION_SCREEN_SCOPE = 3
Public Const VISION_SCREEN_TABLE2DGRID = 4
Public Const VISION_SCREEN_TABLE3DGRID = 5
Public Const VISION_SCREEN_STRIPCHARTRECORDER = 6
Public Const VISION_SCREEN_DASHBOARD = 7
Public Const VISION_SCREEN_GAUGE = 8

Public Const VISION_DATAITEM_GROUP = 0
Public Const VISION_DATAITEM_ARRAY1D = 1
Public Const VISION_DATAITEM_ARRAY2D = 2
Public Const VISION_DATAITEM_SCALAR = 3
Public Const VISION_DATAITEM_STATEVARIABLE = 4
Public Const VISION_DATAITEM_TABLE2D = 5
Public Const VISION_DATAITEM_TABLE3D = 6
Public Const VISION_DATAITEM_VIRTUALSCALAR = 7
Public Const VISION_DATAITEM_EDAQ16AI = 8
Public Const VISION_DATAITEM_EDAQ16DI = 9
Public Const VISION_DATAITEM_EDAQ16PI = 10
Public Const VISION_DATAITEM_EDAQ16TC = 11
Public Const VISION_DATAITEM_STRING = 12
Public Const VISION_DATAITEM_EMXAI = 13
Public Const VISION_DATAITEM_DAQCHANNEL = 14
Public Const VISION_DATAITEM_CANSIGNAL = 15
Public Const VISION_DATAITEM_EMXTI = 16
